/* IoT HealthStation Kinesis Data Analytics SQL Statement */

CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" 
(deviceid VARCHAR(40), msg VARCHAR(40), avgtemp INTEGER, avghum INTEGER, minhum INTEGER, mintemp INTEGER, avgbpm INTEGER, avgox INTEGER);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM "deviceid", "MSG",
  AVG("temperaturef") OVER TEN_SECOND_SLIDING_WINDOW AS avgtemp, 
  AVG("humidity")  OVER TEN_SECOND_SLIDING_WINDOW AS avghum, 
  MIN("humidity")  OVER TEN_SECOND_SLIDING_WINDOW AS minhum, 
  MIN("temperaturef") OVER TEN_SECOND_SLIDING_WINDOW AS mintemp,
  AVG("bpm")  OVER TEN_SECOND_SLIDING_WINDOW AS avgbpm,
  AVG("spo2") OVER TEN_SECOND_SLIDING_WINDOW AS avgox 
FROM "SOURCE_SQL_STREAM_001"
 
WINDOW TEN_SECOND_SLIDING_WINDOW AS (
  PARTITION BY "deviceid"
  RANGE INTERVAL '2' SECOND PRECEDING);